# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analyser.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 0, "", "analyser.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import data_pb2 as data__pb2
from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0e\x61nalyser.proto\x12\x0ciart.indexer\x1a\ndata.proto\x1a\x0c\x63ommon.proto"V\n\nPluginInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12,\n\x08settings\x18\x03 \x03(\x0b\x32\x1a.iart.indexer.PluginConfig"\x14\n\x12ListPluginsRequest"B\n\x10ListPluginsReply\x12.\n\x0cplugin_infos\x18\x01 \x03(\x0b\x32\x18.iart.indexer.PluginInfo"=\n\x0e\x41nalyseRequest\x12+\n\nplugin_run\x18\x01 \x01(\x0b\x32\x17.iart.indexer.PluginRun";\n\x0c\x41nalyseReply\x12+\n\x07results\x18\x01 \x03(\x0b\x32\x1a.iart.indexer.PluginResult2\xa5\x01\n\x08\x41nalyser\x12R\n\x0clist_plugins\x12 .iart.indexer.ListPluginsRequest\x1a\x1e.iart.indexer.ListPluginsReply"\x00\x12\x45\n\x07\x61nalyse\x12\x1c.iart.indexer.AnalyseRequest\x1a\x1a.iart.indexer.AnalyseReply"\x00\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "analyser_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_PLUGININFO"]._serialized_start = 58
    _globals["_PLUGININFO"]._serialized_end = 144
    _globals["_LISTPLUGINSREQUEST"]._serialized_start = 146
    _globals["_LISTPLUGINSREQUEST"]._serialized_end = 166
    _globals["_LISTPLUGINSREPLY"]._serialized_start = 168
    _globals["_LISTPLUGINSREPLY"]._serialized_end = 234
    _globals["_ANALYSEREQUEST"]._serialized_start = 236
    _globals["_ANALYSEREQUEST"]._serialized_end = 297
    _globals["_ANALYSEREPLY"]._serialized_start = 299
    _globals["_ANALYSEREPLY"]._serialized_end = 358
    _globals["_ANALYSER"]._serialized_start = 361
    _globals["_ANALYSER"]._serialized_end = 526
# @@protoc_insertion_point(module_scope)
