# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: collection.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'collection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63ollection.proto\x12\nfileharbor\"?\n\x0fIndexDefinition\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\x05\x12\x10\n\x08\x64istance\x18\x03 \x01(\t\"R\n\x14\x43ollectionAddRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12,\n\x07indexes\x18\x03 \x03(\x0b\x32\x1b.fileharbor.IndexDefinition\"\x17\n\x15\x43ollectionAddResponse\"\'\n\x17\x43ollectionDeleteRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x1a\n\x18\x43ollectionDeleteResponse\"\x17\n\x15\x43ollectionListRequest\"\x18\n\x16\x43ollectionListResponse\"\x0e\n\x0cQueryRequest\"\x0f\n\rQueryResponse2\xc2\x02\n\nCollection\x12L\n\x03\x61\x64\x64\x12 .fileharbor.CollectionAddRequest\x1a!.fileharbor.CollectionAddResponse\"\x00\x12U\n\x06\x64\x65lete\x12#.fileharbor.CollectionDeleteRequest\x1a$.fileharbor.CollectionDeleteResponse\"\x00\x12O\n\x04list\x12!.fileharbor.CollectionListRequest\x1a\".fileharbor.CollectionListResponse\"\x00\x12>\n\x05query\x12\x18.fileharbor.QueryRequest\x1a\x19.fileharbor.QueryResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'collection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INDEXDEFINITION']._serialized_start=32
  _globals['_INDEXDEFINITION']._serialized_end=95
  _globals['_COLLECTIONADDREQUEST']._serialized_start=97
  _globals['_COLLECTIONADDREQUEST']._serialized_end=179
  _globals['_COLLECTIONADDRESPONSE']._serialized_start=181
  _globals['_COLLECTIONADDRESPONSE']._serialized_end=204
  _globals['_COLLECTIONDELETEREQUEST']._serialized_start=206
  _globals['_COLLECTIONDELETEREQUEST']._serialized_end=245
  _globals['_COLLECTIONDELETERESPONSE']._serialized_start=247
  _globals['_COLLECTIONDELETERESPONSE']._serialized_end=273
  _globals['_COLLECTIONLISTREQUEST']._serialized_start=275
  _globals['_COLLECTIONLISTREQUEST']._serialized_end=298
  _globals['_COLLECTIONLISTRESPONSE']._serialized_start=300
  _globals['_COLLECTIONLISTRESPONSE']._serialized_end=324
  _globals['_QUERYREQUEST']._serialized_start=326
  _globals['_QUERYREQUEST']._serialized_end=340
  _globals['_QUERYRESPONSE']._serialized_start=342
  _globals['_QUERYRESPONSE']._serialized_end=357
  _globals['_COLLECTION']._serialized_start=360
  _globals['_COLLECTION']._serialized_end=682
# @@protoc_insertion_point(module_scope)
