log_level = "info"

[service]
max_workers = 4
port = 50051
host = "0.0.0.0"

[cache]
path = "/tmp/cache"

[data]
path = "/data/data"


[[inference]]
name = "ray"
type = "RayInferenceServer"

[[compute_plugin]]
name = "clip_image_vit-b-32_siglip2-256"
type = "ClipImageEmbeddingFeature"
inference = "ray"

[compute_plugin.params]
inference.requirements = ["torch", "open_clip_torch", "imageio", "transformers"]
multicrop = true
max_dim = 0
min_dim = 244
embedding_size = 768
model = "hf-hub:timm/ViT-B-32-SigLIP2-256"


[[compute_plugin]]
name = "clip_text_vit-b-32_siglip2-256"
type = "ClipTextEmbeddingFeature"
inference = "ray"

[compute_plugin.params]
inference.requirements = ["torch", "open_clip_torch", "imageio", "transformers"]
embedding_size = 768
model = "hf-hub:timm/ViT-B-32-SigLIP2-256"


[[index]]
name = "default"
payload_fields = ["meta/*", "collection/*"]

[index.indexer_plugin]
type = "QDrantIndexer"

[index.indexer_plugin.params]
host = "localhost"
port = 6333
grpc.port = 50151
grpc.host = "localhost"

# Clip SigLIP 2
## Index
[[index.indexing_plugin]]
index_name = "clip_image_siglib2"
compute_plugin = "clip_image_vit-b-32_siglip2-256"
input_mapping = { "*" = "image" }
fields = ["image"]

[[index.indexing_plugin]]
index_name = "clip_text_siglib2"
compute_plugin = "clip_text_vit-b-32_siglip2-256"
input_mapping = { "*" = "text" }
fields = ["meta/*"]

## Search
[[index.search_plugin]]
index_name = "clip_image_siglib2"
compute_plugin = "clip_image_vit-b-32_siglip2-256"
input_mapping = { "*" = "image" }
fields = ["image"]

[[index.search_plugin]]
index_name = "clip_text_siglib2"
compute_plugin = "clip_text_vit-b-32_siglip2-256"
input_mapping = { "*" = "text" }
fields = ["text"]

[[index.search_plugin]]
index_name = "clip_image_siglib2"
compute_plugin = "clip_text_vit-b-32_siglip2-256"
input_mapping = { "*" = "text" }
fields = ["text"]
