log_level = "info"

[service]
max_workers = 4
port = 50051
host = "0.0.0.0"

[[search_index]]
name = "default"

[[search_index.plugin]]
name = "clip_text"
type = "ClipTextEmbeddingFeature"
fields = ["meta/*"]

[search_index.plugin.params]
inference.requirements = ["torch", "open_clip_torch", "imageio", "transformers"]

[[search_index.plugin]]
name = "clip_image"
type = "ClipImageEmbeddingFeature"
fields = ["image"]

[search_index.plugin.params]
inference.requirements = ["torch", "open_clip_torch", "imageio", "transformers"]
multicrop = true
max_dim = 0
min_dim = 244
model = "xlm-roberta-base-ViT-B-32"
pretrained = "laion5b_s13b_b90k"
